<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/normalize.css"/>
    <link rel="stylesheet" href="css/main.css"/>
    <title>Tache</title>
</head>

<body>

<main class="flex">
    <section class="flex">
        <article>
            <form action="controller/supp.php" method="POST">
            <ul>
            </ul>
                <input type="submit" name="supprimer" value="suprimer">
        </form>
        </article>
    </section>

    <section class="form flex">
        <form action="controller/add.php" method="POST">
            <fieldset>
                <legend>Tâche</legend>
                <label for="titre">Titre :</label>
                <input type="text" id="titre" name="titre" required="required" placeholder="Titre de la tâche">
                <label for="description">Déscription de la tâche :</label>
                <textarea id="description" name="description" rows="5" cols="33" wrap=off
                          placeholder="Détail de la tâche"></textarea>
                <label for="date">Date de fin :</label>
                <div class="flex date">
                    <select id="jour" name="jour">
                        <?php
                        for ($jour = 1; $jour < 32; $jour++) {
                            echo "<option value=" . $jour . ">" . $jour . "</option>";
                        }
                        ?>
                    </select>
                    <select id="mois" name="mois">
                        <?php
                        for ($i = 0; $i < sizeof($arrayMois); $i++) {
                            echo "<option value=" . ($i+1) . ">" . $arrayMois[$i] . "</option>";
                        }
                        ?>
                    </select>
                    <select name="annee">
                        <?php
                        for ($year = date('Y');$year < date('Y')+ 5; $year++){
                            echo "<option value=" . $year . ">" . $year ."</option>";
                        }?>
                    </select>
                </div>
                <label for="level">Priorité :</label>
                <div class="flex">
                    <INPUT type="radio" name="level" value="basse" required="required">Basse
                    <INPUT type="radio" name="level" value="normal" required="required">Normal
                    <INPUT type="radio" name="level" value="haute" required="required">Haute
                </div>
                <input type="submit" name="enregistrer" value="Enregistrer">
            </fieldset>
        </form>
    </section>
</main>
</body>
<footer>

</footer>

</html>
